version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: echo pip-one
      - run: sudo pip install -r requirements.txt
      - run: echo pystest-one
      - run: pytest hello_ci.py -v

workflows:
  main:
    jobs:
      - build-and-test
